site_name: Cognition and Memory Lab
nav:
  - Home: index.md
  - Research: research.md
  - People: people.md
  - Publications: publications.md
  - Presentations: presentations.md
  - Resources: resources.md
  - Join us!: interest.md
  - Contact: contact.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tabs.sticky 
    - navigation.expand
  palette:
    scheme: slate
markdown_extensions:
  - attr_list