site_name: Cognition and Memory Lab
nav:
  - Home: index.md
  - Research: research.md
  - People: people.md
  - Publications: publications.md
  - Presentations: presentations.md
  - Resources: resources.md
  - Join us!: interest.md
  - Contact: contact.md
theme:
  name: material
  features:
    - navigation.expand
    - navigation.tabs
    - navigation.top
    - navigation.tabs.sticky 
    - navigation.indexes
    - toc.integrate
    - navigation.expand
    
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle: 
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
      primary: deep-purple
      accent: deep-orange
  
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      primary: deep-purple
      accent: deep-orange

# extra_css:
#  - stylesheets/extra.css


markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
